### ISSUE TITLE
Network architecture

### ISSUE THREAD

**Issue by ChuanWang90** [joseabernal/iSeg2017-nic_vicorob#1]
Hi,

I am trying to understand which network you used here.Do you have any file or publication where you describe your network?

Thank you very much.

**Comment by joseabernal** [comment]
For understanding the architecture itself, I recommend checking the following article "Dolz, J. et al. 3D fully convolutional networks for subcortical segmentation in MRI: A large-scale study. Neuroimage, 2017". However, this is our implementation of it. Thus some things are not the same. More details in the following link.

[iseg2017-presentation.pdf](https://github.com/joseabernal/iSeg2017-nic_vicorob/files/1469984/iseg2017-presentation.pdf)

**Comment by joseabernal** [comment]
[iseg2017-presentation.pdf](https://github.com/joseabernal/iSeg2017-nic_vicorob/files/1469983/iseg2017-presentation.pdf)

**Comment by ChuanWang90** [comment]
Thanks for your answer @joseabernal Now it is clear to me. Great job!
