### ISSUE TITLE
I question in build_set()

### ISSUE THREAD

**Issue by Kaido0** [joseabernal/iSeg2017-nic_vicorob#2]
![image](https://user-images.githubusercontent.com/20549461/36089781-83d98312-1018-11e8-8df9-8287fe21672d.png)
Should not be added `reshape((9*9*9,num_classes))`?

**Comment by joseabernal** [comment]
Indeed. This implementation worked on Keras 2. What I do know is to use flatten() on label_patches[i].

**Comment by joseabernal** [comment]
The code has been updated. Thanks!
