### ISSUE TITLE
Query regarding class_mapper

### ISSUE THREAD

**Issue by adideshpande** [joseabernal/iSeg2017-nic_vicorob#5]
I'm trying to understand the iSeg2017.ipynb notebook and in the `Problem Configuration`, it is stated that -

`class_mapper = {0 : 0, 10 : 0, 150 : 1, 250 : 2}`
`class_mapper_inv = {0 : 0, 1 : 10, 2 : 150, 3 : 250}`

Here, in the `class_mapper`, shouldn't it be `{0: 0, 10: 1, 150: 2, 250: 3}` instead of what you have written in the code? 

If not, could you please let me know why the keys 0, as well as 10, have the value 0?

Thanks in advance

**Comment by joseabernal** [comment]
You are right. In principle, it should be as you suggest. Nonetheless, we observed that higher performance could be achieved by combining background and CSF (See slide 10 in the presentation)
[iseg2017-presentation.pdf](https://github.com/joseabernal/iSeg2017-nic_vicorob/files/3158317/iseg2017-presentation.pdf)
